INSERT INTO users (name, age) VALUES ("Bob", 22);
INSERT INTO users (name, age) VALUES ("Sue", 25);
INSERT INTO users (name, age) VALUES ("Mary", 23);
INSERT INTO users (name, age) VALUES ("Joe", 10);
INSERT INTO users (name, age) VALUES ("Mac", 14);
INSERT INTO users (name, age) VALUES ("Rob", 33);
INSERT INTO users (name, age) VALUES ("Tod", 40);
INSERT INTO users (name, age) VALUES ("Mark", 65);
INSERT INTO users (name, age) VALUES ("Sal", 69);
INSERT INTO users (name, age) VALUES ("Cat", 55);
INSERT INTO users (name, age) VALUES ("Rea", 43);
INSERT INTO users (name, age) VALUES ("Sid", 42);
INSERT INTO users (name, age) VALUES ("Molly", 51);
INSERT INTO users (name, age) VALUES ("Cid", 19);
INSERT INTO users (name, age) VALUES ("Tina", 21);
INSERT INTO users (name, age) VALUES ("Ben", 33);
INSERT INTO users (name, age) VALUES ("Matt", 39);
INSERT INTO users (name, age) VALUES ("Holly", 80);
INSERT INTO users (name, age) VALUES ("Stan", 27);
INSERT INTO users (name, age) VALUES ("Rah", 20);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mystery Machine", "technology", 100000, "1/2/20", "6/6/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Awesome Comic", "comics", 5000, "3/12/20", "4/12/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("A Dumb Movie", "film", 6000000, "5/20/20", "1/6/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Some Video Game Rip-off", "games", 90000, "3/11/20", "4/20/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Board Game Clone", "games", 2000000, "8/2/20", "9/6/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("My Special Book", "books", 8000, "2/14/20", "7/14/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Exciting Video Game", "games", 3000000, "3/21/20", "9/12/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Indie Darling", "film", 65000, "11/25/20", "12/7/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cancelled Show: The Movie", "film", 90000000, "6/2/20", "6/6/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Gross Cookbook", "books", 1000, "12/25/20", "5/9/21");

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 7, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 9, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 14, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 15, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 17, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (55, 18, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (85, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 11, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (55, 16, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 17, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 19, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 6);